name: Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20', '1.21.x' ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.version }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Check format
        run: |
          go fmt ./...
          git diff --exit-code

      - name: Lint
        run: go run honnef.co/go/tools/cmd/staticcheck@latest ./...
